"""
Dimension-level analysis for the LLM input-strategy experiment.

This module analyses performance across the six compliance
dimensions using the evaluation dataset generated by
analysis.quality_analysis.

Gold-standard N/A cases are excluded, matching the quality
evaluation methodology.

Metrics:
    - Precision
    - Recall
    - F1
    - Accuracy
    - Evaluable cases
    - Correct predictions
"""

from pathlib import Path
import sys

import pandas as pd
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

RESULTS_DIR = PROJECT_ROOT / "results"

QUALITY_DIR = RESULTS_DIR / "quality"
DIMENSION_DIR = RESULTS_DIR / "dimension"

EVALUATION_FILE = (
    QUALITY_DIR / "evaluation_dataset.csv"
)

DIMENSION_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

STRATEGY_ORDER = [
    "S1_full",
    "S2_sections",
    "S3_fields",
    "S4_hybrid",
    "S5_extended",
]

STRATEGY_LABELS = {
    "S1_full": "S1 – Full text",
    "S2_sections": "S2 – Section filtering",
    "S3_fields": "S3 – Field extraction",
    "S4_hybrid": "S4 – Hybrid",
    "S5_extended": "S5 – Extended extraction",
}

DIMENSION_ORDER = [
    "revenue_concentration",
    "expense_spike",
    "pass_through_risk",
    "unallowable_expenditure",
    "audit_opinion",
    "going_concern",
]

DIMENSION_LABELS = {
    "revenue_concentration":
        "Revenue concentration",

    "expense_spike":
        "Expense spike",

    "pass_through_risk":
        "Pass-through risk",

    "unallowable_expenditure":
        "Unallowable expenditure",

    "audit_opinion":
        "Audit opinion",

    "going_concern":
        "Going concern",
}

REQUIRED_COLUMNS = [
    "experiment_doc_id",
    "gold_document_id",
    "strategy",
    "dimension",
    "experiment_dimension",
    "gold_label",
    "predicted_label",
    "gold_binary",
    "predicted_binary",
]


def load_evaluation_dataset():

    if not EVALUATION_FILE.exists():

        raise FileNotFoundError(
            f"Evaluation dataset not found:\n"
            f"{EVALUATION_FILE}\n\n"
            "Run analysis.quality_analysis first."
        )

    df = pd.read_csv(
        EVALUATION_FILE
    )

    print(
        f"Evaluation records loaded: "
        f"{len(df)}"
    )

    missing = [
        column
        for column in REQUIRED_COLUMNS
        if column not in df.columns
    ]

    if missing:

        raise ValueError(
            "The evaluation dataset is missing "
            "required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing
            )
        )

    return df


def prepare_dimension_dataset(df):

    result = df.copy()

    result["gold_label"] = (
        result["gold_label"]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    result["predicted_label"] = (
        result["predicted_label"]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    result = result[
        result["gold_label"] != "N/A"
    ].copy()

    if result.empty:

        raise ValueError(
            "No evaluable observations remain "
            "after excluding gold-standard N/A cases."
        )

    result["gold_binary"] = pd.to_numeric(
        result["gold_binary"],
        errors="coerce",
    )

    result["predicted_binary"] = pd.to_numeric(
        result["predicted_binary"],
        errors="coerce",
    )

    if (
        result["gold_binary"].isna().any()
        or
        result["predicted_binary"].isna().any()
    ):

        raise ValueError(
            "Binary classification fields contain "
            "non-numeric values."
        )

    return result


def calculate_dimension_strategy_metrics(
    df
):

    rows = []

    for strategy in STRATEGY_ORDER:

        for dimension in DIMENSION_ORDER:

            subset = df[
                (
                    df["strategy"]
                    == strategy
                )
                &
                (
                    df["dimension"]
                    == dimension
                )
            ].copy()

            if subset.empty:
                continue

            y_true = (
                subset["gold_binary"]
                .astype(int)
            )

            y_pred = (
                subset["predicted_binary"]
                .astype(int)
            )

            total_cases = len(
                subset
            )

            correct = int(
                (
                    y_true == y_pred
                ).sum()
            )

            precision = precision_score(
                y_true,
                y_pred,
                zero_division=0,
            )

            recall = recall_score(
                y_true,
                y_pred,
                zero_division=0,
            )

            f1 = f1_score(
                y_true,
                y_pred,
                zero_division=0,
            )

            accuracy = accuracy_score(
                y_true,
                y_pred,
            )

            positive_gold = int(
                y_true.sum()
            )

            positive_predicted = int(
                y_pred.sum()
            )

            rows.append({

                "strategy":
                    strategy,

                "strategy_label":
                    STRATEGY_LABELS[
                        strategy
                    ],

                "dimension":
                    dimension,

                "dimension_label":
                    DIMENSION_LABELS[
                        dimension
                    ],

                "evaluable_cases":
                    total_cases,

                "gold_positive_cases":
                    positive_gold,

                "predicted_positive_cases":
                    positive_predicted,

                "correct_predictions":
                    correct,

                "precision":
                    precision,

                "recall":
                    recall,

                "f1":
                    f1,

                "accuracy":
                    accuracy,
            })

    return pd.DataFrame(
        rows
    )


def calculate_dimension_summary(
    metrics_df
):

    rows = []

    for dimension in DIMENSION_ORDER:

        subset = metrics_df[
            metrics_df["dimension"]
            == dimension
        ]

        if subset.empty:
            continue

        rows.append({

            "dimension":
                dimension,

            "dimension_label":
                DIMENSION_LABELS[
                    dimension
                ],

            "strategies_evaluated":
                len(subset),

            "mean_precision":
                subset["precision"].mean(),

            "mean_recall":
                subset["recall"].mean(),

            "mean_f1":
                subset["f1"].mean(),

            "mean_accuracy":
                subset["accuracy"].mean(),

            "total_evaluable_cases":
                subset["evaluable_cases"].sum(),

            "total_gold_positive_cases":
                subset[
                    "gold_positive_cases"
                ].sum(),
        })

    return pd.DataFrame(
        rows
    )


def calculate_dimension_case_counts(
    df
):

    rows = []

    for dimension in DIMENSION_ORDER:

        subset = df[
            df["dimension"]
            == dimension
        ]

        if subset.empty:
            continue

        gold_counts = (
            subset["gold_label"]
            .value_counts()
        )

        rows.append({

            "dimension":
                dimension,

            "dimension_label":
                DIMENSION_LABELS[
                    dimension
                ],

            "evaluable_cases":
                len(subset),

            "gold_CLEAR":
                int(
                    gold_counts.get(
                        "CLEAR",
                        0,
                    )
                ),

            "gold_FLAG":
                int(
                    gold_counts.get(
                        "FLAG",
                        0,
                    )
                ),

            "gold_ESCALATE":
                int(
                    gold_counts.get(
                        "ESCALATE",
                        0,
                    )
                ),
        })

    return pd.DataFrame(
        rows
    )


def print_dimension_metrics(
    metrics_df
):

    print("\n" + "=" * 70)
    print("DIMENSION × STRATEGY PERFORMANCE")
    print("=" * 70)

    display_columns = [
        "strategy",
        "dimension_label",
        "evaluable_cases",
        "gold_positive_cases",
        "predicted_positive_cases",
        "precision",
        "recall",
        "f1",
        "accuracy",
    ]

    print(
        metrics_df[
            display_columns
        ].to_string(
            index=False,
            float_format=lambda x: f"{x:.3f}",
        )
    )


def print_dimension_summary(
    summary_df
):

    print("\n" + "=" * 70)
    print("DIMENSION SUMMARY")
    print("=" * 70)

    print(
        summary_df.to_string(
            index=False,
            float_format=lambda x: f"{x:.3f}",
        )
    )


def print_case_counts(
    counts_df
):

    print("\n" + "=" * 70)
    print("GOLD-STANDARD CASE COUNTS BY DIMENSION")
    print("=" * 70)

    print(
        counts_df.to_string(
            index=False
        )
    )


def run_dimension_analysis():

    print("=" * 70)
    print("DIMENSION ANALYSIS")
    print("=" * 70)

    raw_df = (
        load_evaluation_dataset()
    )

    df = (
        prepare_dimension_dataset(
            raw_df
        )
    )

    print("\n" + "=" * 70)
    print("DATASET")
    print("=" * 70)

    print(
        f"Evaluable observations: "
        f"{len(df)}"
    )

    print(
        f"Strategies: "
        f"{df['strategy'].nunique()}"
    )

    print(
        f"Dimensions: "
        f"{df['dimension'].nunique()}"
    )

    metrics_df = (
        calculate_dimension_strategy_metrics(
            df
        )
    )

    summary_df = (
        calculate_dimension_summary(
            metrics_df
        )
    )

    counts_df = (
        calculate_dimension_case_counts(
            df
        )
    )

    print_dimension_metrics(
        metrics_df
    )

    print_dimension_summary(
        summary_df
    )

    print_case_counts(
        counts_df
    )

    output_files = {

        "metrics":
            DIMENSION_DIR
            / "dimension_strategy_metrics.csv",

        "summary":
            DIMENSION_DIR
            / "dimension_summary.csv",

        "case_counts":
            DIMENSION_DIR
            / "dimension_case_counts.csv",
    }

    metrics_df.to_csv(
        output_files["metrics"],
        index=False,
    )

    summary_df.to_csv(
        output_files["summary"],
        index=False,
    )

    counts_df.to_csv(
        output_files["case_counts"],
        index=False,
    )

    print("\n" + "=" * 70)
    print("FILES SAVED")
    print("=" * 70)

    for path in output_files.values():
        print(path)

    print("\n" + "=" * 70)
    print("DIMENSION ANALYSIS COMPLETE")
    print("=" * 70)

    return {
        "metrics": metrics_df,
        "summary": summary_df,
        "case_counts": counts_df,
    }


if __name__ == "__main__":
    run_dimension_analysis()