"""
Error analysis for the LLM input-strategy experiment.

This module analyses classification errors using the evaluation
dataset generated by analysis.quality_analysis.

Positive class:
    FLAG / ESCALATE

Negative class:
    CLEAR / N/A

Gold-standard N/A cases are excluded, matching the quality
evaluation methodology.

Outputs are written to:

    results/errors/
"""

from pathlib import Path
import sys

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


RESULTS_DIR = PROJECT_ROOT / "results"

QUALITY_DIR = RESULTS_DIR / "quality"
ERROR_DIR = RESULTS_DIR / "errors"

EVALUATION_FILE = (
    QUALITY_DIR / "evaluation_dataset.csv"
)

ERROR_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


STRATEGY_ORDER = [
    "S1_full",
    "S2_sections",
    "S3_fields",
    "S4_hybrid",
    "S5_extended",
]

STRATEGY_LABELS = {
    "S1_full": "S1 – Full text",
    "S2_sections": "S2 – Section filtering",
    "S3_fields": "S3 – Field extraction",
    "S4_hybrid": "S4 – Hybrid",
    "S5_extended": "S5 – Extended extraction",
}

DIMENSION_ORDER = [
    "revenue_concentration",
    "expense_spike",
    "pass_through_risk",
    "unallowable_expenditure",
    "audit_opinion",
    "going_concern",
]

DIMENSION_LABELS = {
    "revenue_concentration": "Revenue concentration",
    "expense_spike": "Expense spike",
    "pass_through_risk": "Pass-through risk",
    "unallowable_expenditure": "Unallowable expenditure",
    "audit_opinion": "Audit opinion",
    "going_concern": "Going concern",
}

POSITIVE_LABELS = {
    "FLAG",
    "ESCALATE",
}

REQUIRED_COLUMNS = [
    "experiment_doc_id",
    "gold_document_id",
    "strategy",
    "dimension",
    "experiment_dimension",
    "gold_label",
    "predicted_label",
    "gold_binary",
    "predicted_binary",
]


def load_evaluation_dataset():

    if not EVALUATION_FILE.exists():

        raise FileNotFoundError(
            f"Evaluation dataset not found:\n"
            f"{EVALUATION_FILE}\n\n"
            "Run analysis.quality_analysis first."
        )

    df = pd.read_csv(
        EVALUATION_FILE
    )

    print(
        f"Evaluation records loaded: "
        f"{len(df)}"
    )

    missing_columns = [
        column
        for column in REQUIRED_COLUMNS
        if column not in df.columns
    ]

    if missing_columns:

        raise ValueError(
            "The evaluation dataset is missing "
            "required columns:\n"
            + "\n".join(
                f"  - {column}"
                for column in missing_columns
            )
        )

    return df


def prepare_evaluable_cases(df):

    result = df.copy()

    result["gold_label"] = (
        result["gold_label"]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    result["predicted_label"] = (
        result["predicted_label"]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    result = result[
        result["gold_label"] != "N/A"
    ].copy()

    if result.empty:

        raise ValueError(
            "No evaluable cases remain after "
            "excluding gold-standard N/A cases."
        )

    result["gold_binary"] = pd.to_numeric(
        result["gold_binary"],
        errors="coerce",
    )

    result["predicted_binary"] = pd.to_numeric(
        result["predicted_binary"],
        errors="coerce",
    )

    if (
        result["gold_binary"].isna().any()
        or
        result["predicted_binary"].isna().any()
    ):

        raise ValueError(
            "gold_binary or predicted_binary contains "
            "non-numeric values."
        )

    valid_binary = {0, 1}

    if not set(
        result["gold_binary"].unique()
    ).issubset(valid_binary):

        raise ValueError(
            "gold_binary contains values other than 0/1."
        )

    if not set(
        result["predicted_binary"].unique()
    ).issubset(valid_binary):

        raise ValueError(
            "predicted_binary contains values other than 0/1."
        )

    result["error_type"] = "Unknown"

    result.loc[
        (
            result["gold_binary"] == 1
        )
        &
        (
            result["predicted_binary"] == 1
        ),
        "error_type",
    ] = "True Positive"

    result.loc[
        (
            result["gold_binary"] == 0
        )
        &
        (
            result["predicted_binary"] == 0
        ),
        "error_type",
    ] = "True Negative"

    result.loc[
        (
            result["gold_binary"] == 0
        )
        &
        (
            result["predicted_binary"] == 1
        ),
        "error_type",
    ] = "False Positive"

    result.loc[
        (
            result["gold_binary"] == 1
        )
        &
        (
            result["predicted_binary"] == 0
        ),
        "error_type",
    ] = "False Negative"

    unknown = result[
        result["error_type"] == "Unknown"
    ]

    if not unknown.empty:

        raise ValueError(
            "Some observations could not be classified "
            "as TP, TN, FP, or FN."
        )

    result["is_error"] = (
        result["error_type"]
        .isin(
            {
                "False Positive",
                "False Negative",
            }
        )
    )

    result["strategy_label"] = (
        result["strategy"]
        .map(STRATEGY_LABELS)
    )

    result["dimension_label"] = (
        result["dimension"]
        .map(DIMENSION_LABELS)
    )

    return result


def calculate_overall_error_summary(df):

    rows = []

    for strategy in STRATEGY_ORDER:

        subset = df[
            df["strategy"] == strategy
        ]

        if subset.empty:
            continue

        total = len(
            subset
        )

        true_positive = (
            subset["error_type"]
            .eq("True Positive")
            .sum()
        )

        true_negative = (
            subset["error_type"]
            .eq("True Negative")
            .sum()
        )

        false_positive = (
            subset["error_type"]
            .eq("False Positive")
            .sum()
        )

        false_negative = (
            subset["error_type"]
            .eq("False Negative")
            .sum()
        )

        rows.append({
            "strategy": strategy,

            "strategy_label": STRATEGY_LABELS[
                strategy
            ],

            "total_evaluable": total,

            "true_positive": true_positive,

            "true_negative": true_negative,

            "false_positive": false_positive,

            "false_negative": false_negative,

            "total_errors": (
                false_positive
                + false_negative
            ),

            "error_rate": (
                (
                    false_positive
                    + false_negative
                )
                / total
            ),
        })

    return pd.DataFrame(
        rows
    )


def calculate_dimension_errors(df):

    rows = []

    for strategy in STRATEGY_ORDER:

        for dimension in DIMENSION_ORDER:

            subset = df[
                (
                    df["strategy"]
                    == strategy
                )
                &
                (
                    df["dimension"]
                    == dimension
                )
            ]

            if subset.empty:
                continue

            true_positive = (
                subset["error_type"]
                .eq("True Positive")
                .sum()
            )

            true_negative = (
                subset["error_type"]
                .eq("True Negative")
                .sum()
            )

            false_positive = (
                subset["error_type"]
                .eq("False Positive")
                .sum()
            )

            false_negative = (
                subset["error_type"]
                .eq("False Negative")
                .sum()
            )

            total = len(
                subset
            )

            rows.append({
                "strategy": strategy,

                "strategy_label": STRATEGY_LABELS[
                    strategy
                ],

                "dimension": dimension,

                "dimension_label": DIMENSION_LABELS[
                    dimension
                ],

                "evaluable_cases": total,

                "true_positive": true_positive,

                "true_negative": true_negative,

                "false_positive": false_positive,

                "false_negative": false_negative,

                "total_errors": (
                    false_positive
                    + false_negative
                ),

                "error_rate": (
                    (
                        false_positive
                        + false_negative
                    )
                    / total
                ),
            })

    return pd.DataFrame(
        rows
    )


def calculate_dimension_error_totals(df):

    rows = []

    for dimension in DIMENSION_ORDER:

        subset = df[
            df["dimension"] == dimension
        ]

        if subset.empty:
            continue

        false_positive = (
            subset["error_type"]
            .eq("False Positive")
            .sum()
        )

        false_negative = (
            subset["error_type"]
            .eq("False Negative")
            .sum()
        )

        rows.append({
            "dimension": dimension,

            "dimension_label": DIMENSION_LABELS[
                dimension
            ],

            "evaluable_cases": len(
                subset
            ),

            "false_positives": false_positive,

            "false_negatives": false_negative,

            "total_errors": (
                false_positive
                + false_negative
            ),
        })

    return pd.DataFrame(
        rows
    )


def calculate_false_negatives(df):

    columns = [
        "experiment_doc_id",
        "gold_document_id",
        "strategy",
        "strategy_label",
        "dimension",
        "dimension_label",
        "gold_label",
        "predicted_label",
        "gold_binary",
        "predicted_binary",
    ]

    result = df[
        df["error_type"]
        == "False Negative"
    ].copy()

    return (
        result[
            columns
        ]
        .sort_values(
            [
                "strategy",
                "dimension",
                "experiment_doc_id",
            ]
        )
        .reset_index(
            drop=True
        )
    )


def calculate_false_positives(df):

    columns = [
        "experiment_doc_id",
        "gold_document_id",
        "strategy",
        "strategy_label",
        "dimension",
        "dimension_label",
        "gold_label",
        "predicted_label",
        "gold_binary",
        "predicted_binary",
    ]

    result = df[
        df["error_type"]
        == "False Positive"
    ].copy()

    return (
        result[
            columns
        ]
        .sort_values(
            [
                "strategy",
                "dimension",
                "experiment_doc_id",
            ]
        )
        .reset_index(
            drop=True
        )
    )


def calculate_positive_case_coverage(df):

    positive_gold = df[
        df["gold_binary"] == 1
    ].copy()

    if positive_gold.empty:
        return pd.DataFrame()

    rows = []

    group_columns = [
        "experiment_doc_id",
        "gold_document_id",
        "dimension",
    ]

    for (
        experiment_doc_id,
        gold_document_id,
        dimension,
    ), group in positive_gold.groupby(
        group_columns
    ):

        gold_label = (
            group["gold_label"]
            .iloc[0]
        )

        row = {
            "experiment_doc_id":
                experiment_doc_id,

            "gold_document_id":
                gold_document_id,

            "dimension":
                dimension,

            "dimension_label":
                DIMENSION_LABELS.get(
                    dimension,
                    dimension,
                ),

            "gold_label":
                gold_label,
        }

        for strategy in STRATEGY_ORDER:

            strategy_case = group[
                group["strategy"]
                == strategy
            ]

            if strategy_case.empty:

                row[
                    strategy
                ] = "MISSING"

            else:

                row[
                    strategy
                ] = (
                    strategy_case[
                        "predicted_label"
                    ]
                    .iloc[0]
                )

        rows.append(
            row
        )

    coverage = pd.DataFrame(
        rows
    )

    for strategy in STRATEGY_ORDER:

        coverage[
            f"{strategy}_detected"
        ] = (
            coverage[strategy]
            .isin(
                POSITIVE_LABELS
            )
        )

    return coverage


def calculate_missed_positive_cases(
    coverage
):

    if coverage.empty:
        return pd.DataFrame()

    rows = []

    for strategy in STRATEGY_ORDER:

        detected_column = (
            f"{strategy}_detected"
        )

        missed = coverage[
            ~coverage[
                detected_column
            ]
        ].copy()

        for _, row in missed.iterrows():

            rows.append({
                "strategy": strategy,

                "strategy_label": STRATEGY_LABELS[
                    strategy
                ],

                "experiment_doc_id":
                    row[
                        "experiment_doc_id"
                    ],

                "gold_document_id":
                    row[
                        "gold_document_id"
                    ],

                "dimension":
                    row[
                        "dimension"
                    ],

                "dimension_label":
                    row[
                        "dimension_label"
                    ],

                "gold_label":
                    row[
                        "gold_label"
                    ],

                "predicted_label":
                    row[
                        strategy
                    ],
            })

    return pd.DataFrame(
        rows
    )


def calculate_document_errors(df):

    rows = []

    for (
        experiment_doc_id,
        strategy,
    ), group in df.groupby(
        [
            "experiment_doc_id",
            "strategy",
        ]
    ):

        false_positive = (
            group["error_type"]
            .eq("False Positive")
            .sum()
        )

        false_negative = (
            group["error_type"]
            .eq("False Negative")
            .sum()
        )

        rows.append({
            "experiment_doc_id":
                experiment_doc_id,

            "strategy": strategy,

            "strategy_label": STRATEGY_LABELS[
                strategy
            ],

            "evaluable_cases": len(
                group
            ),

            "false_positives": false_positive,

            "false_negatives": false_negative,

            "total_errors": (
                false_positive
                + false_negative
            ),

            "error_rate": (
                (
                    false_positive
                    + false_negative
                )
                / len(group)
            ),
        })

    return pd.DataFrame(
        rows
    )


def run_error_analysis():

    print("=" * 60)
    print("ERROR ANALYSIS")
    print("=" * 60)

    raw_df = (
        load_evaluation_dataset()
    )

    df = (
        prepare_evaluable_cases(
            raw_df
        )
    )

    print("\n" + "=" * 60)
    print("EVALUABLE CASES")
    print("=" * 60)

    print(
        f"Total evaluable observations: "
        f"{len(df)}"
    )

    print(
        f"Strategies: "
        f"{df['strategy'].nunique()}"
    )

    print(
        f"Documents: "
        f"{df['experiment_doc_id'].nunique()}"
    )

    print(
        f"Dimensions: "
        f"{df['dimension'].nunique()}"
    )

    overall_df = (
        calculate_overall_error_summary(
            df
        )
    )

    print("\n" + "=" * 60)
    print("OVERALL ERROR SUMMARY")
    print("=" * 60)

    print(
        overall_df.to_string(
            index=False,
            float_format=lambda x: f"{x:.3f}",
        )
    )

    dimension_df = (
        calculate_dimension_errors(
            df
        )
    )

    print("\n" + "=" * 60)
    print("ERRORS BY DIMENSION AND STRATEGY")
    print("=" * 60)

    print(
        dimension_df.to_string(
            index=False,
            float_format=lambda x: f"{x:.3f}",
        )
    )

    dimension_totals_df = (
        calculate_dimension_error_totals(
            df
        )
    )

    print("\n" + "=" * 60)
    print("TOTAL ERRORS BY DIMENSION")
    print("=" * 60)

    print(
        dimension_totals_df.to_string(
            index=False
        )
    )

    fn_df = (
        calculate_false_negatives(
            df
        )
    )

    print("\n" + "=" * 60)
    print("FALSE NEGATIVES")
    print("=" * 60)

    print(
        f"Total false negatives: "
        f"{len(fn_df)}"
    )

    if not fn_df.empty:

        print(
            fn_df.to_string(
                index=False
            )
        )

    fp_df = (
        calculate_false_positives(
            df
        )
    )

    print("\n" + "=" * 60)
    print("FALSE POSITIVES")
    print("=" * 60)

    print(
        f"Total false positives: "
        f"{len(fp_df)}"
    )

    if not fp_df.empty:

        print(
            fp_df.to_string(
                index=False
            )
        )

    coverage_df = (
        calculate_positive_case_coverage(
            df
        )
    )

    print("\n" + "=" * 60)
    print("GOLD-STANDARD POSITIVE CASE COVERAGE")
    print("=" * 60)

    if coverage_df.empty:

        print(
            "No FLAG/ESCALATE gold-standard "
            "cases were found."
        )

    else:

        total_positive = len(
            coverage_df
        )

        print(
            f"Total gold-standard positive cases: "
            f"{total_positive}"
        )

        for strategy in STRATEGY_ORDER:

            detected = int(
                coverage_df[
                    f"{strategy}_detected"
                ].sum()
            )

            print(
                f"{strategy}: "
                f"{detected}/{total_positive} "
                f"positive cases detected "
                f"({detected / total_positive:.1%})"
            )

    missed_df = (
        calculate_missed_positive_cases(
            coverage_df
        )
    )

    print("\n" + "=" * 60)
    print("MISSED GOLD-STANDARD POSITIVE CASES")
    print("=" * 60)

    if missed_df.empty:

        print(
            "No missed positive cases."
        )

    else:

        print(
            missed_df.to_string(
                index=False
            )
        )

    document_df = (
        calculate_document_errors(
            df
        )
    )

    output_files = {

        "overall":
            ERROR_DIR
            / "overall_error_summary.csv",

        "dimension_strategy":
            ERROR_DIR
            / "dimension_strategy_errors.csv",

        "dimension_totals":
            ERROR_DIR
            / "dimension_error_totals.csv",

        "false_negatives":
            ERROR_DIR
            / "false_negatives.csv",

        "false_positives":
            ERROR_DIR
            / "false_positives.csv",

        "positive_coverage":
            ERROR_DIR
            / "gold_positive_case_coverage.csv",

        "missed_positive":
            ERROR_DIR
            / "missed_positive_cases.csv",

        "document":
            ERROR_DIR
            / "document_error_summary.csv",

        "case_level":
            ERROR_DIR
            / "case_level_error_classification.csv",
    }

    overall_df.to_csv(
        output_files["overall"],
        index=False,
    )

    dimension_df.to_csv(
        output_files["dimension_strategy"],
        index=False,
    )

    dimension_totals_df.to_csv(
        output_files["dimension_totals"],
        index=False,
    )

    fn_df.to_csv(
        output_files["false_negatives"],
        index=False,
    )

    fp_df.to_csv(
        output_files["false_positives"],
        index=False,
    )

    coverage_df.to_csv(
        output_files["positive_coverage"],
        index=False,
    )

    missed_df.to_csv(
        output_files["missed_positive"],
        index=False,
    )

    document_df.to_csv(
        output_files["document"],
        index=False,
    )

    df.to_csv(
        output_files["case_level"],
        index=False,
    )

    print("\n" + "=" * 60)
    print("FILES SAVED")
    print("=" * 60)

    for path in output_files.values():
        print(path)

    print("\n" + "=" * 60)
    print("ERROR ANALYSIS COMPLETE")
    print("=" * 60)

    return {
        "case_level": df,
        "overall": overall_df,
        "dimension_strategy": dimension_df,
        "dimension_totals": dimension_totals_df,
        "false_negatives": fn_df,
        "false_positives": fp_df,
        "positive_coverage": coverage_df,
        "missed_positive": missed_df,
        "document": document_df,
    }


if __name__ == "__main__":
    run_error_analysis()